doc-style/action.yml
This pull-request avoids having all workflows inside the `.github/workflows` dir by forcing users to pass tokens and secrets to the actions.
It does not introduce security vulnerabilities as the tokens are executed at runtime and not store in this repository.
=> FIX: inputs secrets

doc-build/action.yml
As per [failing actions in ansys-templates](https://github.com/ansys/ansys-templates/actions/runs/3329549652/jobs/5506934463), it looks like the logic behind using Xvfb is not properly working.
This pull-request solves for some syntax errors and uses explicit conditional examples.
=> FIX: doc-build input names

doc-deploy-stable/action.yml
This pull-request guarantees that only the major and minor numbers of the semantic version tag are used during the stable doc deployment.
=> FIX: parsing tag version

doc/source/build-actions/index.rst
Fix minor typo in build library action doc. 
Character ">" was missing at the end in line 28.
=> FIX: typo in Build library action documentation

_release-pypi/action.yml, _setup-python/action.yml, build-ci-wheels/action.yml, build-library/action.yml, build-wheelhouse/action.yml, code-style/action.yml, doc-build/action.yml, doc-deploy-stable/action.yml, tests-pytest/action.yml
This pull-request solves #56 by adding a "private" action for setting up Python. This action is then reused across all the different actions in the repository.
=> FEAT: add private _setup-python action and force cache usage

.github/workflows/ci_cd.yml, doc-deploy-to-repo/action.yml
I just remembered that secrets cannot be used in reusable actions. They need to be passed as arguments. This solves the latest CI failures related with this issue.
=> FIX: secrets usage in doc-deploy-to-repo

.github/workflows/ci_cd.yml, release-github/action.yml
Solve #57 by publishing during a GitHub release all generated artifacts.
=> FEAT: publish all artifacts during GitHub release

doc/source/tests-actions/index.rst
Make sure example takes advantage of `matrix`. I will cherry-pick this into the `release/1.0`, so it is fixed in the documentation of that branch too.
=> DOC: fix example bug

doc-deploy-stable/action.yml
As per [pygeomemtry failing actions](https://github.com/pyansys/pygeometry/actions/runs/3487427530/jobs/5835475424). This will be cherry-picked to the release/1.0. I will also move the v1 tag.
=> FIX: do not use cache in doc-deploy-stable

.github/workflows/ci_cd.yml, build-wheelhouse/action.yml, release-github/action.yml
Zip action was updated over the weekend to solve issues with Node JS 12 version. Now it is using Node JS 16. However, tag ``@v1`` was not updated when releasing and for making use of this new version we need to add the minor version to the call. Dependabot won't update it automatically either since we are only specifying the major version.
=> Update zip action to v1.1

scripts/version_mapper.py, tests/tests_scripts/release/announcement.html, tests/tests_scripts/test_version_mapper.py
Fix #80.
Repositories should implement an `announcement.html` template in their `gh-pages` branch and within the `release/` folder.
The content of the `announcement.html` should look like:
```html
<p>You are not reading the most recent version of this documentation. Latest stable release is <a href="https://actions.pyansys.com/release/{version}">{version}</a></p>.
```
This way, the version script can format that template to the desired version.
=> FEAT: enable outdated versions announcement logic

.gitignore, scripts/version_mapper.py
Namespace object has no attribute 'announcement_file', which will create error. Resolves the above.
=> Rename namespace for argument

scripts/version_mapper.py
The "version_mapper.py" script gets downloaded from "main" branch. The latest changes introduced in #84 were being used, thus, by the "v1" branch.
This changes check whether the announcement file exists or not. If it is not present, the script terminates and forgets about the announcement.
=> FIX: ignore missing announcement.html

scripts/version_mapper.py
Last additions to #90. The action will include now the "announcement.html" rendered file within each key subdir of the outdated release folders.
=> FIX: recursively add announcement.html to the different folders

scripts/version_mapper.py
I introduced a bug in previous pull-request. The logic required an "or" instead of an "and". Nevertheless, this changes may be more readable than using negations.
=> FIX: valid name logic

scripts/version_mapper.py
This pull-request fixes one last bug regarding the announcment. The new code guarantees that not only private folders are excluded but also their sub-directories.
Also, the whole stable release folder gets ignored by default.
=> FIX: recursively add announcement.html

scripts/version_mapper.py
In #94, the glob pattern did not ignored the latest stable release. In addition, it did not considered the base directory for the different outdated releases, only their subdirectories. This pull-request solves those issues.
=> FIX: do not ignore base release folders

doc-deploy-stable/action.yml
User should able to decide the number of versions to get rendered in multi-doc. Fix #99
=> Add an input for the render last version for multiple documentation in workflow

.flake8, .gitignore, doc-style/action.yml, doc/Makefile, doc/source/build-actions/examples/build-ci-wheels-basic.yml, doc/source/build-actions/examples/build-library-basic.yml, doc/source/build-actions/examples/build-wheelhouse-basic.yml, doc/source/build-actions/index.rst, doc/source/conf.py, doc/source/doc-actions/examples/doc-build-basic.yml, doc/source/doc-actions/examples/doc-build-dependencies.yml, doc/source/doc-actions/examples/doc-build-xvfb.yml, doc/source/doc-actions/examples/doc-deploy-dev-basic.yml, doc/source/doc-actions/examples/doc-deploy-stable-basic.yml, doc/source/doc-actions/examples/doc-deploy-to-repo-basic.yml, doc/source/doc-actions/index.rst, doc/source/licenses-actions/examples/check-licenses-basic.yml, doc/source/licenses-actions/index.rst, doc/source/release-actions/examples/release-github-basic.yml, doc/source/release-actions/examples/release-pypi-private-basic.yml, doc/source/release-actions/examples/release-pypi-public-basic.yml, doc/source/release-actions/examples/release-pypi-test-basic.yml, doc/source/release-actions/index.rst, doc/source/style-actions/examples/code-style-basic.yml, doc/source/style-actions/examples/doc-style-basic.yml, doc/source/style-actions/index.rst, doc/source/tests-actions/examples/tests-pytest-basic.yml, doc/source/tests-actions/examples/tests-pytest-optimized.yml, doc/source/tests-actions/index.rst, requirements/requirements_doc.txt
Fix #82 by adding more examples and using Jinja to create the dropdowns and fixing the version. In addition, the accepted licenses and ignored packages are dynamically loaded too, see:
=> DOC: add more examples and automate their rendering

doc-deploy-stable/action.yml
Reverting the changes made in #111. The version used in that PR was the one from the library using the actions, not the one from the actions. There is not way for the action to know where version they belong to when executed from the CI/CD of a third party repo. I bet the best way to go is to manually change this every time we do a new stable release.
=> FIX: scripts version

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml, doc/styles/Vocab/ANSYS/accept.txt
The following pull-request allows to clean the gh-pages branch. This was originally done by using the `clean` parameter in the old `gh-pages-deploy` action.
However, as a consequence of migrating to the `dev/` and `release/` structure, this needs to be performed trough and additional step inside development and stable doc deploy workflows.
=> FIX: clear gh-pages branch before pushing

doc-deploy-dev/action.yml
As the title.
We should probably give many options for filtering the artifacts.
I'm using the default ``actions/download-artifact`` action unless one of the arguments is used, but I'm happy to drop it.
=> Allowing download artifacts from other workflows

build-ci-wheels/action.yml, build-library/action.yml, build-wheelhouse/action.yml, check-licenses/action.yml, code-style/action.yml, doc-build/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml, doc-deploy-to-repo/action.yml, doc-style/action.yml, tests-pytest/action.yml
Adding ``checkout`` optional argument to all the actions (almost all actually).
I also added an ``skip-install` condition to the ``doc-build`` checkout step. To be consistent with the ``check-license`` behavior.
Also, I'm not sure what is the recommend approach if:
``if: ${{ input.checkout == 'true' }}`` or ``if: input.checkout == 'true'``
Close #123
=> Making checkout optional

doc-deploy-dev/action.yml
The `checkout` input parameter was missing in the `doc-deploy-dev` action. This pull-request fixes this bug.
=> FIX: missing input parameter

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Fixes #148 by using [ouch](https://github.com/ouch-org/ouch) for using the right decompressing tool. No additional dependencies are required.
=> FEAT: use ouch for artifact decompression

.pre-commit-config.yaml, doc-deploy-dev/action.yml
Fixes the recent issues in:
* Pyfluent visualization: https://github.com/pyansys/pyfluent-visualization/actions/runs/3992912227/jobs/6849174814
* PyAEDT: https://github.com/pyansys/pyaedt/actions/runs/3992907653
* Other internal repositories that just upgraded to pyansys/actions@v3.
I feel the conflict is being caused because the value for the `workflow` is not behaving as expected. Hence, I went with this "duplicated" logic. This is the original logic from pyansys/actions@v2.0.7, which has been proven to work.
I do not like to keep patching stuff in here but I did not see other option for the moment. Once we agree on https://github.com/pyansys/actions/discussions/141, everything will be unified for @v4.
=> FIX: download artifacts from desired workflow

doc-deploy-dev/action.yml
Continuation of #150. This introduces the actions/download-artifact, which is the one that originally got implemented. This way both dawidd6/download-artifact and actions/download-artifact coexist in v3.
=> FIX: allow the usage of actions/download-artifact again

release-github/action.yml
Seen in https://github.com/pyansys/pygeometry/actions/runs/4132811802/jobs/7142191585#step:3:1437
When attempting to perform GitHub release, the wheels are not found because of the artifact naming convention. This has to be fixed and patched released
=> Wheels should be uploaded - error in naming

.github/workflows/ci_cd.yml
Improves the current pipelines to guarantee that the development documentation gets published only after building docs and passing all tests. Also, stable documentation is only published after a successfully release.
=> CI: improve pipelines

.github/dependabot.yml, doc/source/conf.py, requirements/requirements_doc.txt
This pull-request updates the documentation dependencies. Also, I noticed that dependabot was pointing to the wrong ecosystem for the Python requirements. Fixing this too.
=> MAINT: update doc dependencies

.github/workflows/ci_cd.yml
This pull-request adds an extra step in the code style to verify that private actions do not point to main. By private actions I mean reusable actions that we implemented to simplify more complex ones.
=> CI: verify private actions do not point to main when releasing

_logging/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Related with #142. Includes a new action named `_logging` that contains three different levels: error (red), warning (yellow) and info (green).
As an example, consider this actions log: https://github.com/pyansys/test-multiversion/actions/runs/4245246509/jobs/7380502179
Update. Now the color code is echoed is included directly in the message to avoid the logs showing any variables.
=> FEAT: add logging action

_release-pypi/action.yml, release-github/action.yml, release-pypi-private/action.yml, release-pypi-public/action.yml, release-pypi-test/action.yml
Fix #138, fix #139 and fix #140 by allowing to download additional artifacts. Related to #178 too.
=> FEAT: allow additional artifacts and dry-runs for critical workflows

build-library/action.yml
This pull-request updates third party actions to the their major versions. Note that not all actions are following this approach.
=> MAINT: update to major versions

release-github/action.yml
As per the issues found in https://github.com/ansys/ansys-sphinx-theme/actions/runs/4284451985/jobs/7461503095.
=> FIX: release-github syntax

doc-build/action.yml
Fixes the logic when installing system dependencies in the `doc-build`.
=> FIX: installing system deps in doc-build

hk-package-clean-except/action.yml, hk-package-clean-untagged/action.yml
Reported by @greschd. Previous implementation was only working with Python 3.11. This one should work everywhere.
=> Solving bug with Package creation dates

.github/dependabot.yml
As per pull-request title, this ensures that dependabot opens any pull request following the "maint: ..." title.
=> chore: force dependabot to follow commit style

_doc-gen-sitemap/action.yml, doc-deploy-stable/action.yml
Fix #242 by adding an action named `_doc-gen-sitemap` that generates a `sitemap.xml` file when deploying the stable documentation.
You can test this logic locally by using the following shell script:
```bash
#!/bin/bash
cname="actions.docs.pyansys.com"
html_dir="doc/_build/html"
website="https://www.${cname}"
input_dir=${html_dir}
output="sitemap.xml"
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > $output
echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> $output
echo "  <url>" >> $output
echo "    <loc>$website</loc>" >> $output
echo "    <lastmod>$(date +%Y-%m-%dT%H:%M:%S+00:00)</lastmod>" >> $output
echo "    <changefreq>daily</changefreq>" >> $output
echo "    <priority>1.0</priority>" >> $output
echo "  </url>" >> $output
while IFS= read -r -d '' file; do …
```
=> feat: add generate sitemap action

_doc-gen-versions-page/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Fix #252.
This pull-request guarantees that the content inside of the desired HTML tag gets override in favor of the Versions page. It also makes sure that the URL are actual HTML links by using the `<a>` tag.
I must confess I am not satisfied with this implementation. The reason is that, so far, multi-version documentation is "agnostic" to the theme you are using. That is why we need to accept this HTML tag to exactly now which is the element containing the main information of the page.
Use the following script and HTML file to reproduce locally. Feel free to modify the unique HTML tag containing the main info of the page to see how this works.
```bash
#!/bin/bash
html_file="index.html"
html_tag="section"
cname="cname.com"
tmp_file="temp.html" # Add variable for temporary file …
```
=> fix: versions page generation

_doc-gen-versions-page/action.yml
As per title, it ensures that the versions page is listed in descending order.
=> feat: reverse in descending order

doc-build/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml, tests-pytest/action.yml
Includes the `-y` flag when performing an `apt-get install` to ensure that the CI/CD process does not hang or die because the lack of user input.
=> fix: yes to all queries in apt-get install

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
This pull-request ensures that all binaries installed by `cargo` get added to the path of the current shell session.
That's the default situation with cargo. However, we have experienced some issues so let us make it explicit its addition to the path.
=> fix: ensure cargo binaries are in PATH

build-wheelhouse/action.yml
Because of `$()` if there is an error while importing the library, the exception/error is hidden because it does not affect the parent process. 
With this PR, we check that the variable has ben properly created which means that the package can be imported properly.
Closes #275
=> fix: check proper import and version variable

build-wheelhouse/action.yml, doc/source/build-actions/examples/build-wheelhouse-basic.yml
Fix #280 by retrieving the library version from its name using the `importlib.metadata` module. Once this is merged, a deprecation should be added in @v4.0.
=> feat: stop asking for library-namespace

doc-build/action.yml, tests-pytest/action.yml
Implements #270 by introducing support for ``poetry`` and ``setuptools`` for the following actions that install a project with some additional dependencies:
- ansys/actions/test-pytest
- ansys/actions/doc-build
=> feat: support poetry build system in tests

build-wheelhouse/action.yml
Fixes #290 by introducing a warning in the documentation. Since we removed the ``library-name`` input parameter, it is no longer possible to reference it in the workflow. Thus, we can not check if the user just passed it. GitHub is the one taking care of this warning.
=> docs: add warning admonition

build-wheelhouse/action.yml
Continuation of #302. Fixes the multi-line docstring in the action.
=> docs: fix admonition rendering

branch-name-style/action.yml
This pull-request documents in a `note` admonition the allowed branch name prefixes.
=> docs: document allowed prefixes for branch name style action

branch-name-style/action.yml
Continuation of #301. Fixes the rendering of the multi-line docstrings in the description of the action.
=> docs: fix multi-line docstring

doc-deploy-stable/action.yml
This pull-request introduces a syntax fix in the `doc-deploy-stable` action when limiting the number of versions displayed in the drop-down menu.
=> fix: syntax errors

doc-build/action.yml
=> docs: typo in docstring

check-licenses/ignored-packages.txt
The package [ansys-corba](https://github.com/ansys/pymapdl-corba) is currently archived (only-read) and it does not have a valid license (no license at all).
I think, we should add it to the exceptions. Or unarchive it and add a license. I don't mind either.
Reason for this PR:
https://github.com/ansys/pymapdl/actions/runs/5799747218/job/15720419673?pr=2234#step:2:3884
Pinging @jorgepiloto @RobPasMue
=> feat: adding ansys corba to ignored licenses

.github/workflows/ci_cd.yml
Fixes the issues pointed out by @Revathyvenugopal162. This ensures that only for tags following `v*.*.*` the CI/CD pipelines get triggered:
- Fails because multi-version does not ingest `vX`, see https://github.com/ansys/actions/actions/runs/5795010942
- Generates draft PRs because some candidates were already released
=> fix: tag trigger in workflow

doc-build/action.yml
As ttile says - we were missing it when running it with ``xvfb-run``
Also, linkcheck should be the first run - even before html or pdf
=> fix: run linkcheck on xvfb-run for doc-build action

check-licenses/ignored-packages.txt
This package is required by one of our libraries. This library is still under development. The WMI package is using an MIT, see https://pypi.org/project/WMI/. However, because it does not ship with a LICENSE file, it needs to be manually ignored.
```console
Invalid licenses found:
WMI 1.4.9 has http://www.opensource.org/licenses/mit-license.php license
Name                                   Version   License                                            
WMI                                    1.4.9     http://www.opensource.org/licenses/mit-license.php 
```
=> fix: sort ignored packages and add WMI

doc-style/action.yml
This pull-request allows users to specify the Vale version during the doc-style checks. By default, it will use the `2.29.3` version.
=> fix: change default vale version

doc-build/action.yml
Pin awalsh128/cache-apt-pkgs to version 1.3.0. 
v1.3.1 came out today and broke workflows that have requires-xvfb = false
- https://github.com/ansys/pydynamicreporting/actions/runs/6697205595/job/18200293938
- https://github.com/ansys/pre-commit-hooks/actions/runs/6697431280/job/18200960100#step:2:147
=> fix: doc-build action - awalsh128/cache-apt-pkgs version

doc-build/action.yml
This PR adds an option to specify the location of the `requirements.txt` dependency file in the doc building action, since in some cases, we are building documentation in non-python projects and we want to avoid having a requirements file outside of the scope where it's needed.
=> feat: Add requirements file custom path in doc building

check-licenses/ignored-packages.txt
Add OpenAI Python library to ignored packages in the license checker, since it doesn't have the license properly configured in PyPI. It uses Apache license, so it should be fine.
References:
https://github.com/openai/openai-python
https://pypi.org/project/openai/
=> fix: Add openai to ignored licenses

_doc-gen-sitemap/action.yml
Fixes #375 by adding a `/` between the website URL and the page.
=> fix: locator in sitemap action

.github/workflows/ci_cd.yml
Fixes the doc-deploy-index action in the CI/CD to ensure that it points to the main branch.
=> fix: all actions pointing to main branch in main

doc-build/action.yml
As title says. Poetry projects require the make command to run from poetry. This will require a patch release
=> fix: docs build failing for poetry projects

code-style/action.yml, doc/source/style-actions/examples/docker-style-basic.yml, doc/source/style-actions/index.rst, docker-style/action.yml
This PR addresses #381 by :
1. adding an extra action ("docker-style") that can be used to evaluate the Dockerfile(s) associated to a repo;
2. extending action "code-style" by triggering "docker-style" on "docker/Dockerfile" and ".devcontainer/Dockerfile" if the associated directories exist.
It was tested and validated in a sandbox. If you are interested, you can see the CI jobs failing and succeeding when expected (https://github.com/SMoraisAnsys/pyansys-geometry/actions/runs/7628030247/job/21173613810?pr=1).
Here is a summary of the changes:
TLDR
------
- docker-style looks for files named "Dockerfile" in the provided directory (default to "docker"). If one wants to propose and evaluate multiple docker files, then the associated repo must follow a directory oriented architecture (e.g. …
=> feat: add dockerfile linting

doc-style/action.yml, docker-style/action.yml
Previous tests performed on `docker-style` were performed in a context where the repo was already cloned on the runner.
However, when that is not the case, the action does not run since there is nothing to lint and warning messages are raised for nothing (see https://github.com/ansys/pyansys-geometry/actions/runs/7869710413/job/21469384363)
This PR adds an extra step as in `doc-style` to trigger project clone if wanted (default is true).
=> fix: docker directory check

check-vulnerabilities/action.yml
The idea is to be able to hide the output of the GitHub action log.
For public repos, it is visible by anyone and could expose vulnerabilities.
This solution of redirecting the output toward `devnull` is far from optimal but better than letting full access to the log for this action.
=> feat: hide output log

check-vulnerabilities/action.yml
By default the artifacts containing the vulnerability reports should not be updated to not disclose those potential vulnerabilities.
=> feat: add an option to upload the vulnerability reports

.ci/ansys-actions/README.rst, README.rst
The link to the MIT license, https://opensource.org/licenses/MIT, is broken so I replaced it with https://opensource.org/blog/license/mit
Example of where it broke in a workflow: https://github.com/ansys/actions/actions/runs/7995412316/job/21835720195?pr=357#step:2:900
=> fix: replace broken MIT link

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Some progress on #284. This pull-request ensures that the content of the redirection `index.html` file is a valid HTML file.
=> fix: complete HTML file for redirect

.github/workflows/ci_cd.yml, doc-style/action.yml
Includes a deprecation warning indicating users to migrate to Vale v3.
=> feat: add deprecation warning

doc/source/index.rst, doc/source/migration_guide.rst, requirements/requirements_doc.txt
=> docs: adding migration guide

check-vulnerabilities/action.yml, doc/source/migration_guide.rst
=> feat: avoid creating issues on vulnerabilities found (by default)

.pre-commit-config.yaml, LICENSE, _doc-gen-robots/action.yml, _doc-gen-sitemap/action.yml, _doc-gen-versions-page/action.yml, _logging/action.yml, _release-pypi/action.yml, _setup-python/action.yml, branch-name-style/action.yml, build-ci-wheels/action.yml, build-library/action.yml, build-wheelhouse/action.yml, check-licenses/action.yml, check-vulnerabilities/action.yml, code-style/action.yml, commit-style/action.yml, doc-build/action.yml, doc-deploy-dev/action.yml, doc-deploy-index/action.yml, doc-deploy-stable/action.yml, doc-style/action.yml, docker-style/action.yml, hk-package-clean-except/action.yml, hk-package-clean-untagged/action.yml, release-github/action.yml, release-pypi-private/action.yml, release-pypi-public/action.yml, release-pypi-test/action.yml, tests-pytest/action.yml
This pull-request includes a new private action named `_doc-gen-robots`. This action is used by the `doc-deploy-stable` action right after calling the `_doc-gen-sitemap`. Its goal is to allow all robots to crawl a website. Crawlable directories include: `version/dev`, `version/stable`, and `version/X.Y` where `X.Y` is the updated latest stable.
It also ensures that the `sitemap.xml` is listed so crawlers can read it.
=> feat: new _doc-gen-robots action to generate seo-compliant "robots.txt"

code-style/action.yml, tests-pytest/action.yml
=> feat: adapting tests and code-style actions to avoid using venv when called by poetry

tests-pytest/action.yml
=> fix: poetry calls failing

_doc-gen-canonical/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
This pull-request includes a new reusable private action named `_doc-gen-canonical`. Its goal is to ensure that the `<link rel="canonical" href="..." />` is included in any HTML of the `version/stable` directory.
=> feat: new canonical link action

code-style/action.yml
Ensures the right indentation and YAML style for the warning admonition in the `code-style` action.
=> fix: code-style description

doc/source/migrations/docs-changelog-setup.rst
The changelog had docs/changelog.d in its comment, but it should be doc/changelog.d
=> fix: Incorrect path in doc-changelog instructions

doc-changelog/action.yml
Trailing whitespace in the title caused an infinite loop between the changelog action and pre-commit.ci fixing the fragment file by removing the trailing whitespace. This fix uses xargs to remove extra whitespace in the PR title
1. Fragment file is added to the PR https://github.com/ansys/pymechanical/actions/runs/8483508864/job/23244782632?pr=669
2. Merged in main & fragment file wasn't updated https://github.com/ansys/pymechanical/actions/runs/8483553847/job/23244904355?pr=669
3. Title changed (still contains trailing whitespace) & fragment file updated: https://github.com/ansys/pymechanical/actions/runs/8483590918/job/23245005569?pr=669
Closes #436
=> fix: doc-changelog action infinite loop with pre-commit.ci

doc-changelog/action.yml
Backticks in titles were erased in the changelog fragment file & also caused infinite loops in pyansys-geometry
Correctly detects backticks: [test with `backticks` · ansys/pymechanical@c007805 (github.com)](https://github.com/ansys/pymechanical/actions/runs/8509562415/job/23306827024?pr=671)
Correctly detects backticks and extra whitespace: [test with `backticks` and extra spaces · ansys/pymechanical@6bd46c1 (github.com)](https://github.com/ansys/pymechanical/actions/runs/8510073370/job/23306905123?pr=671)
=> fix: changelog action backtick in title

commit-style/action.yml
As title says.
Closes #446
Note: option `headerPattern` seems to be related to "how to parse" a commit title to retrieve the `type`, `scope` and `description`. Thus it seems more adequate to use option `types` instead.
=> feat: allow upper case in commit-style

branch-name-style/action.yml
This action is otherwise incompatible with projects using pre-commit.ci.
Workaround is https://github.com/ansys/pyansys-geometry/pull/1108 but I would rather have it skipped by the action directly since it affects multiple projects.
=> feat: ignore pre-commit.ci branch name on branch-name-style action

doc-build/action.yml
Seems like #453 got merged before I could change the version it was pointing to. It was left pointing to the development branch to let anyone test the action on their repo as it was performed in https://github.com/ansys/pyansys-geometry/pull/1068.
I should have left a warning to notify of that, sorry for not thinking about it.
=> fix: wrong action version in doc-build

doc/source/migrations/docs-changelog-setup.rst
Adding an example for how to replace `"ansys.<product>.<library>"` in the doc-changelog migration guide
=> docs: add package phrase replacement example in doc-changelog guide

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Fixes the issues originated when a local link starts with `h`, or `t`, or `p`.
=> fix: regex for fixing links in landing page

doc-build/action.yml
Closes #461 
Order was inverted... leading to incapability to cache deps
=> fix: order of checkout and Python install has to be reversed

commit-style/action.yml, doc/source/migrations/index.rst
Changes include a minor patch for the documentation of `commit-style` and updates the new features of `v6`.
=> docs: update v6 changes

doc/source/migrations/docs-style-vale-version-update.rst
New vocabularies path has to be modified for code spell hook if it uses `accept.txt`
=> docs: Add `code spell` hook changes in vale migration guide

doc/source/migrations/docs-changelog-setup.rst
Following https://github.com/ansys/pyansys-geometry/pull/1138 I believe it is also interesting that users learn how to add it to their documentation
=> docs: implementing changelog as part of the documentation

_doc-gen-canonical/action.yml
This pull-request ensures the canonical link gets added right before the main `</head>`.
=> fix: canonical link injection in HTML files

branch-name-style/action.yml, commit-style/action.yml, doc/source/style-actions/index.rst
=> docs: fixing links and removing empty table

build-library/action.yml, doc/source/migrations/index.rst, doc/styles/.gitignore
As title says. Coming from an internal request by @anscfrisson. Some libraries may have long descriptions that are causing the twine check to validate. These libraries will never be published to PyPI in this state (since PyPI upload will probably fail). However it will allow them to continue to build the library using our actions.
=> feat: enable validate-build option to build-library action

doc-style/action.yml
As per a private discussion, we are forcing the `doc-style` action to check the Vale configuration layout according to the selected version.
=> fix: fail doc-style action when wrong Vale config is present

doc-style/action.yml
Reverting #470 commited to main - if is failing. See https://github.com/ansys/actions/actions/runs/8833187453/job/24251985324
=> fix: vale check

doc/source/migrations/docs-deploy-changelog-setup.rst
=> fix: remove unnecessary curly brackets in doc-deploy-changelog docs

.github/workflows/ci_cd.yml, doc-style/action.yml
doc-style fails in main if pyproject.toml doesn't exist in the repository
=> fix: check pyproject.toml file exists before opening it

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
In this PR, I added an input to `doc-deploy-dev` and `doc-deploy-stable` so we can skip when needed the step to overwrite the index.html page. 
It will be used in some internal projects.
Tested [here](https://github.com/ansys-internal/glow-engine/actions/runs/9220336792) successfully.
_** Correct the name of the branch used in [PR#492](https://github.com/ansys/actions/pull/492)_
=> feat: make optional use latest index in landing page

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
This PR addresses a search issue in the deployment script by updating the search action path in the landing page. Previously, the search action was set to `search.html`, causing search functionality to look for the incorrect file. With this fix, the search action path is updated to `version/stable/search.html` for stable versions or `version/dev/search.html` for development versions. This ensures that the search functionality points to the correct location, resolving the search issue effectively.
=> fix: update doc deploy actions to to correct local search path on landing page

doc-deploy-changelog/action.yml
=> feat: allow upper case in doc-deploy-changelog

.github/dependabot.yml
Solves for #418 by implementing the new dependabot syntax. This version of dependabot is still in beta mode.
=> feat: update dependabot to new wildcard syntaxt

doc-deploy-changelog/action.yml, doc/source/migrations/docs-changelog-setup.rst, doc/styles/config/vocabularies/ANSYS/accept.txt
Updated the doc-changelog migration guide to clarify setting up the release notes in the `CHANGELOG.md` file versus the documentation (`changelog.rst`). Although a couple of the steps are repeated in the "release notes in your documentation" and "release notes in `CHANGELOG.md`" sections, I think it's clearer. 
Previously, you would have to set up everything for the `CHANGELOG.md` configuration, and then change most of what you had set up if you want to include it in your documentation instead.
=> chore: enhance doc-changelog migration guide

.github/dependabot.yml
This pull-request is a continuation of #500. Uses the `directories` key in both ecosystems to investigate the issues from https://github.com/ansys/actions/network/updates
=> fix: investigate dependabot syntax

build-wheelhouse/action.yml
The checkout remains the default, but can be skipped if set to false. This can be useful when there are prior steps to build elements that should be packed into the wheelhouse. For example, some projects have a step to build cython .pyd files and those .pyd files should go into the wheel file. The checkout step would purge the repo and clear the files from the previous build step. Now, projects that have this requirement can opt to skip the checkout.
=> feat: add an optional input for checkout so it can be skipped, if needed

_doc-build-windows/action.yml
Current Windows implementation was zipping the entire "doc/build..." folder structure. We are only interested in the contents inside the "html" folder
=> fix: only compress content inside html folder

_doc-build-windows/action.yml
As title says - let's leave optional targets after HTML and PDF builds
=> chore: optional targets run at the end

doc-style/action.yml
After a discussion on #432, we thought about allowing users to specify the location of their documentation files. With these changes, projects with `doc/` and `examples/` folders can now run:
```yml
doc-style:
name: "Doc style ${{ matrix.folder }}"
runs-on: ubuntu-latest
strategy:
matrix:
folder: ["doc", "examples"]
fail-fast: false
steps:
- uses: ansys/actions/doc-style@v6
with:
files: ${{ matrix.folder }}
vale-config: ${{ matrix.folder }}/.vale.ini
token: ${{ secrets.GITHUB_TOKEN }}
```
=> feat: allow users to indicate files dir

doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Updates the version of the `peaceiris/actions-gh-pages` to v4. Opening this as a fix so we can cherry-pick it into `release/6.1` and perform a patch.
=> fix: peaceiris/actions-gh-pages@v4 version

doc-changelog/action.yml
Changed the commit message to be `chore: adding changelog file $fragment`, where fragment is the name of the file
=> fix: make doc-changelog commit message compliant

_doc-build-linux/action.yml, _doc-build-windows/action.yml, doc-build/action.yml
Duplicate of #517 to use a branch name passing CI.
---
Thanks @dipinknair for noticing that some inputs in the private actions were not needed.
This comes from the fact that two steps are performed before running any private action (checkout and setup-python) Since both private actions (windows and linux) are not involved in python setup and git install + clone, this PR removes the following inputs from the private actions:
- python-version
- use-python-cache
- checkout
=> refactor: remove non needed inputs

release-pypi-private/action.yml
Fix: #524 .
Previously, it was only possible to upload the release to the private Ansys pypi.
Now it should be possible to release to a different index.
=> fix: Upload to various private indexes.

doc-deploy-changelog/action.yml
Updates the changelog file and deletes the towncrier fragments on the main branch directly. This is mainly to fix these issues in the pre-commit hooks repo when doing releases: [203](https://github.com/ansys/pre-commit-hooks/issues/203), [171](https://github.com/ansys/pre-commit-hooks/issues/171)
use-main-branch: true
- [Skips creating the PR into main with the deleted towncrier fragments & updated changelog file](https://github.com/ansys-internal/actions-sandbox/actions/runs/10149117952/job/28063309800)
- [Successful run after changelog is updated & fragment files are removed from main](https://github.com/ansys-internal/actions-sandbox/actions/runs/10149121860/job/28063325213)
default (update-release-branch is true and use-main-branch is false)
- release/x.y branch doesn't exist
- …
=> feat: doc-deploy-changelog update main branch option

doc-changelog/parse_pr_title.py
Adjusted the logic to get the changelog section from the cc_type_changelog_dict when there's an exclamation point in the conventional commit type string from the PR title. It looks like amannn/action-semantic-pull-request [allows the breaking changes symbol (!)](https://github.com/amannn/action-semantic-pull-request/blob/main/README.md#examples)
=> feat: doc-changelog allow breaking changes symbol in conventional commit type

_doc-build-linux/action.yml, _doc-build-windows/action.yml, _doc-gen-canonical/action.yml, _doc-gen-robots/action.yml, _doc-gen-sitemap/action.yml, _doc-gen-versions-page/action.yml, _logging/action.yml, _release-pypi/action.yml, branch-name-style/action.yml, build-ci-wheels/action.yml, build-library/action.yml, build-wheelhouse/action.yml, check-licenses/action.yml, check-vulnerabilities/action.yml, code-style/action.yml, commit-style/action.yml, doc-build/action.yml, doc-changelog/action.yml, doc-deploy-changelog/action.yml, doc-deploy-dev/action.yml, doc-deploy-index/action.yml, doc-deploy-stable/action.yml, doc-style/action.yml, doc/source/doc-actions/index.rst, docker-style/action.yml, release-github/action.yml, release-pypi-private/action.yml, release-pypi-public/action.yml, release-pypi-test/action.yml, tests-pytest/action.yml
Closes #531 
Also adding proper formatting to all inputs.
=> fix: changelog actions docs missing

doc-deploy-changelog/action.yml
- Consolidate "update-release-branch" and "update-main-branch" into one input: "release-from-main"
- By default, "release-from-main" is false, meaning the action assumes the tag was created on a release branch
- Included a detailed description for "release-from-main" to clarify the different options
=> fix: use one input to specify the tag the branch was created from in doc-deploy-changelog

doc-deploy-changelog/action.yml
Move the description of the doc-deploy-changelog process to the main description and simplify the description under release-from-main
=> chore: move the description in doc-deploy-changelog

_doc-build-linux/action.yml, _doc-build-windows/action.yml
While updating #543 conflict, I found out that the parameter `needs-quarto` was not correctly defined in private actions.
=> fix: needs-quarto is required parameter

_doc-build-windows/action.yml
In private action `_doc-build-windows`, set step "Check Quarto Version" to use `shell: powershell` instead of `shell: bash`.
=> fix: use powershell in quarto check (windows)

.github/dependabot.yml
The issue with the current glob pattern for `dependabot` is that these patterns can not be in conflict between different ecosystems. That is, if two ecosystems are checking for the same file, dependabot fails, see https://github.com/ansys/actions/network/updates/20639306/jobs
=> ci: fix dependabot glob pattern

doc-changelog/action.yml, doc-deploy-changelog/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Add a logging warning for the actions that will require a bot-user and bot-email as inputs for v8. I'm not sure if this is the correct way to go about it, so please let me know if there are alternatives that make more sense. Thanks!
=> feat: add logging warning about bot secrets requirement for v8

.ci/ansys-actions/pyproject.toml, .github/workflows/ci_cd.yml
Use a trusted publisher instead of twine for releases and add the bot user & email secrets
=> chore: use trusted publisher in ci_cd

.github/workflows/ci_cd.yml, _release-pypi/action.yml
Fixes the issues raised in https://github.com/ansys/actions/actions/runs/10960208443, where the version being pushed was already present in the Test PyPI.
=> fix: skip release to PyPI test if version exists

.github/workflows/ci_cd.yml
Follow up of #570 which fixed the environment used for test PyPI.
The problem with the fix is that we still end up with messages referring to the deployment in the PR discussion.
This PR consists in removing the environment used in test PyPI. Note that:
- the current environment used (`tests`) is an empty shell;
- the previous one (`release`) shouldn't have been used for testing if we want to keep the protection rules.
=> ci: remove environment from test PyPI

_doc-build-linux/action.yml, _doc-build-windows/action.yml, check-vulnerabilities/action.yml, code-style/action.yml, doc-build/action.yml, tests-pytest/action.yml
Following the work on #543, it seems that there was a need for three things:
- better handling of unexpected behavior when working with VMs, see https://github.com/ansys/actions/issues/559;
- better coherence in how we deal with `poetry` and `pip` build backends;
- better handling of the corner case where poetry and the project have shared dependencies with different versions.
This PR aims at tackling those three points by enforcing the use of a virtual environment, even when working with `poetry`.
On top of those changes, the modified actions are now "more compatible" with `poetry`. Before, the default behavior was to use `python -m pip install .` while now we detect the build backend and use `poetry` if appropriate.
> **Note**: following @Andy-Grigg comments, we use a "hack" to ensure …
=> refactor: use virtual environment to be consistent

AUTHORS, CODE_OF_CONDUCT.md, CONTRIBUTORS.md
This pull-request includes some of the metadata files in #581, in particular the `AUTHORS`, `CONTRIBUTORS.md`, and `CODE_OF_CONDUCT.md` ones.
=> docs(metadata): add AUTHORS, CONTRIBUTORS.md, and CODE_OF_CONDUCT.md

README.rst
As title says. The previous README title had the same level as the other sections which led to an odd layout and TOC
=> docs: proper titles on README

doc/source/migrations/index.rst, doc/styles/config/vocabularies/ANSYS/accept.txt
We missed documenting the removal of the `branch-name-style` action in the migration guide. This needs to be cherry-picked.
=> fix(doc): branch-name-sytle action deprecation

code-style/action.yml
Hello!
Most of the time, [our use case](https://github.com/ansys/pydynamicreporting/blob/main/.github/workflows/ci_cd.yml#L32) does not require the --show-diff-on-failure flag which when turned on, it produces a large diff of unwanted output that pollutes the action logs. Thereby, I'd like to propose a flag to turn it off but keep it on by default.
=> feat: Add an input flag to configure diff output in code style checks

doc-deploy-changelog/action.yml
Add a caution message in the body of the PR being merged into main to not merge the PR until the release has been made
Here's a preview:
=> chore: add caution message to doc-deploy-changelog action

build-wheelhouse/action.yml, check-licenses/action.yml, tests-pytest/action.yml
Closes #516 
Testing done in https://github.com/ansys/pyansys-tools-report/pull/219
=> feat: whitelist packages on check-licenses action

check-vulnerabilities/action.yml, code-style/action.yml, tests-pytest/action.yml
Similarly to the issues resolved by https://github.com/ansys/actions/pull/596, the v8 `code-style` action fails on windows runners. See https://github.com/ansys/openapi-common/actions/runs/11208266030/job/31226892848 for example.
This PR applies fixes similar to https://github.com/ansys/actions/pull/596, however that still was failing https://github.com/ansys/openapi-common/actions/runs/11234704576/job/31231061286, in a way that suggests that the virtual envrionment wasn't activated at all.
I've had to change the command from `.venv\\Scripts\\activate` to `source .venv/scripts/activate` for it to actually activate the env and get a successful run https://github.com/ansys/openapi-common/actions/runs/11234704576
=> fix: standardize venv activation in `actions/code-style`

code-style/action.yml
Reported internally. We should pin the pre-commit version we are using (as we did in the past for other python packages we use within our actions). Version 4.x is breaking a lot of hooks in the ecosystem from what has been seen.
=> fix: pre-commit new release causing breaking changes

_logging/action.yml, doc-changelog/action.yml, doc-deploy-changelog/action.yml, doc-deploy-dev/action.yml, doc-deploy-stable/action.yml
Add check to see if bot user or email inputs are empty. If so, log an error message & exit 1. Exiting 1 when logging an error message was applied to the _logging action.
[Exit 1 on error](https://github.com/ansys-internal/actions-sandbox/actions/runs/11278326057/job/31366557792)
[Bot secrets exist, so no error](https://github.com/ansys-internal/actions-sandbox/actions/runs/11278177040/job/31366367645)
Closes #603
=> fix: exit 1 when logging error messages

doc-style/action.yml
As title says. This was modified in https://github.com/errata-ai/vale-action/commit/1262efadd6fde1040255db25589fe57804d785d2 inside the vale-action so now we need to install it manually.
=> fix: install additional deps on doc-style action for rST support

_doc-build-windows/action.yml, doc-build/action.yml
Ensures that `EXPECTED_BUILD_DIR` is defined even if `add-pdf-html-docs-as-assets` is `false`.
Only trigger checking if the expected doc build directory is used, aka `doc/_build`.
Close #622
=> fix: check step in _doc-build-windows

.github/workflows/release.yml
Following the failure of release `v8.1.0`, this PR should fix the problem of performing the rolling release workflow when one didn't create the minor/major release associated. In the case of `v8.1.0`, `v8` was already existing thanks to previous workflows but that was not the case for `v8.1`. The same problem can happen with major release.
> Note: There are two commits here and they propose two approaches to handle that problem. The latest comes from @jacobevansgit and is performed in `ansys-internal` actions. The idea is to add `|| true` to the tag deletion command which ensures that the workflow won't stop even if the tag does not exist. The other approach checks tags and either perform deletion or logs an info, depending on tag existence.
Let me know which approach you prefer
=> ci: fix rolling release

doc-deploy-changelog/action.yml
Added error logging when `doc-deploy-changelog` fails with the following message:
"[ValueError: It seems you've already produced newsfiles for this version?](https://github.com/ansys/pydyna/actions/runs/11935351034/job/33267732404#step:2:634)"
Instead of displaying the above message, it will print an error message with instructions on how to fix it and exit 1:
=> fix: doc-deploy-changelog error handling

check-vulnerabilities/action.yml
Following #646 - @greschd noticed that when using poetry and ``extra-targets`` there is a small problem... ``--with ...`` uninstalls any other deps found and thus causes setuptools not to be present, which is needed by our action to run.
By inverting the installation order, we should be able to fix this.
=> feat: change installation order of deps in check-vulnerabilities action

.github/workflows/ci_cd.yml
Closes #645 
This will skip the label insertion if the change is coming from a forked repository... requires testing but should work.
=> feat: skip label step if coming from a forked repository

doc/source/migrations/docs-changelog-setup.rst
In the code sample provided for the pyproject.toml section  where we add the towncrier statements, `{org-name}` does not appear to be a variable.
`ansys` is hardcoded instead.
I am not against it as it might make our colleagues life easier because most of them will use ansys actions in ansys org.
It might be a slight showstopper for external people using it in an other org. But most likely limited.
Replacing `ansys` by `{org-name}` in the path would work too for me.
=> docs: 'org-name' is not a variable in the code sample provided.

_doc-build-linux/action.yml
Deprecation of actions/upload-artifact is causing failures in (for example) https://github.com/ansys/pyansys-geometry/actions/runs/12695645218/job/35388005982?pr=1617 
This affects the entire ecosystem - patch releasing right away
=> fix: cache-apt-pkgs-action 1.3.1 uses upload-artifact v3 (deprecated)

.ci/ansys-actions/pyproject.toml
Temporary work around for the problem that appeared two days ago with the release-pypi action.
=> ci: update fake repo build system version

README.md
Recent changes in the workflows broke the badge in our README.
=> docs: fix CICD badge in README

.github/workflows/ci_cd_night.yml, doc/source/changelog/711.maintenance.md
Nightly deployment is causing our CNAME to disappear.
=> ci: nightly deployment does not have the CNAME

CONTRIBUTING.md, doc/source/changelog/712.documentation.md
Fix #581 by adding the `CONTRIBUTING.md` file. To unlock the release of ansys/actions@v8.2, the content of this file points to the PyAnsys Developer's Guide. For v9, we can expand this into a dedicated section in the documentation.
=> docs(metadata): add CONTRIBUTING.md

doc/source/changelog/719.documentation.md, release-pypi-private/action.yml, release-pypi-public/action.yml, release-pypi-test/action.yml
Currently the deprecation warning is triggered even for people using the twine token approach. This should fix it.
Note that the private action `_release-pypi` has logs a "notice" if users don't leverage the trusted publisher approach so they complement each other ! :)
=> docs: log deprecation only for trusted publishers

doc-deploy-changelog/action.yml, doc/source/changelog/723.fixed.md
As pointed out by @SMoraisAnsys, https://github.com/ansys/actions/pull/723 I removed the installation of libraries thinking this was not required. However, Towncrier requires Python projects to be installed to retrieve their current version.
=> fix: install for Python libraries

doc/source/changelog/732.fixed.md, python-utils/release_github_utils.py, release-github/action.yml
Use pypandoc to convert rst content to md
- no longer need `rst_to_md_links` and `rst_to_md` functions since we are using `pypandoc.convert_text`
**Release notes body from changelog.rst file with new jinja template**
**Release notes body from changelog.rst file with original jinja template**
**Release notes body from CHANGELOG.md file**
=> fix: release-github body

.github/dependabot.yml, _release-pypi/action.yml, doc/source/changelog/734.miscellaneous.md
Use a SHA instead of a label for `pypa/gh-action-pypi-publish`.
On top of that the changes consist in adding `_release-pypi` to dependabot.
It seems that the expression `"!(requirements)/**/*"` does not cover the repo as it was assumed.
=> refactor: use SHA version for pypa/gh-action-pypi-publish

doc/source/changelog/742.fixed.md, release-github/action.yml
As title says. Experienced issues in https://github.com/ansys/pyansys-geometry/actions/runs/13991469373/job/39179171722
=> fix: sanity check on inputs for release-github action

.github/workflows/ci_cd_release.yml, doc/source/changelog/750.maintenance.md
If the changelog action and the rolling release action run at the same time, you enter race conditions and sometimes, the version might not be available for download. I suggest we put it as a dependent stage.
=> ci: changelog action should depend on rolling release

build-wheelhouse/action.yml, doc/source/changelog/756.fixed.md
We use [pip wheel](https://github.com/ansys/actions/blob/af045ca0e768847401c655294e48fb9981f5dcb1/build-wheelhouse/action.yml#L191) for building wheels in `actions/build-wheelhouse`. `build` and `wheel` packages are not needed dependencies to be able to use `pip wheel` because "wheel" is a command option for pip in this case.
=> fix: drop build and wheel packages

doc/source/changelog/755.documentation.md, doc/source/conf.py
Every two weeks the servers associated to www.x.org are down and our CICD fails because we do have a reference to https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml. This ~fixes~ ignores it.
=> docs: do not check link on www.x.org/*

.github/workflows/ci_cd_release.yml, doc/source/changelog/764.fixed.md
GITHUB_REF and GITHUB_REF_NAME have values following `refs/heads/feature-branch-1` and `feature-branch-1` formats.
=> fix: github-ref

doc/source/changelog/769.documentation.md, doc/source/migrations/index.rst
As title says. We should do a patch release so that the docs get updated on the released version too.
=> docs: fix link

doc/source/changelog/777.dependencies.md, release-github/action.yml
When using the full hash for actions commit I left the old version that was used hoping for an automatic update from dependabot.
However, it seems that the action repo does not always handle new versions as one would expect (e.g. there is no 1.0 version). I checked and the only "big change" was that they moved to `node20` so I'm not expecting any issue with bumping to a newer version.
=> build(actions): update action-gh-release

check-vulnerabilities/requirements.txt, doc/source/changelog/780.maintenance.md
Avoid using marshmallow v4.0.0 otherwise running safety ends up with an exception being triggered:
`Unhandled exception happened: post_dump() got an unexpected keyword argument 'pass_many'`
Here is a failing workflow: https://github.com/ansys/pyacp/actions/runs/14518929119/job/40734794587
Note that this is affecting multiple projects and not only PyACP
=> chore: add upper bound on marshmallow

.github/workflows/ci_cd_pr.yml, check-environment-approval/action.yml, determine-environment-approval/action.yml, doc/source/changelog/776.added.md, doc/source/vulnerability-actions/examples/check-environment-approval.yml, doc/source/vulnerability-actions/index.rst
Following recent developments to add a manual approval for dependabot PR (see #751 and #774), this PR gathers the decision logic of requiring a manual approval or not.
The action allows user to specify which environment they want to use when a workflow is running because either `dependabot[bot]` triggered it or the workflow is associated to a PR of `dependabot[bot]` and `pyansys-ci-bot` is the one triggering the workflow.  Another input is allowed to provide a "skip" environment for other cases.
> [!NOTE]
Currently, passing `skip-manual-check-environment: ''` behaves as if no environment was defined. Therefore, no comment such as the one below appear in the PR conversation.
That was tested in a1d92c8, see below
=> feat: check environment approval

doc-deploy-changelog/action.yml, doc/source/changelog/782.fixed.md
We shouldn't need to install the project -- we can benefit directly from the version and name inputs.
Related to #723 -- not necessary anymore.
Closes #779
=> fix: skip installation on doc-deploy-changelog

doc-deploy-changelog/action.yml, doc/source/changelog/783.fixed.md, towncrier.toml
Fix the issues raised in https://github.com/ansys/actions/actions/runs/14574889354/job/40878852430 by adding the necessary keys in the `towncrier.toml` file.
=> fix: add package key in towncrier.toml

doc-deploy-changelog/action.yml, doc/source/changelog/784.fixed.md
Newline between `TOWNCRIER_DIR` and `TOWNCRIER_NAME` was missing, causing the `TOWNCRIER_DIR` env variable's value to be `doc/source/changelogTOWNCRIER_NAME=ansys.actions.core`
=> fix: Add newline between environment variables in Python

_doc-build-linux/action.yml, _doc-build-windows/action.yml, doc-build/action.yml, doc/source/changelog/791.fixed.md
Quarto v1.7.29 that workflows recently started installing is causing failures, examples:
https://github.com/ansys/pymapdl/actions/runs/14711086308/job/41283486237?pr=3875
https://github.com/ansys/pyaedt/actions/runs/14711189901/job/41283858673?pr=6078
https://github.com/ansys/actions/actions/runs/14713893172/job/41292794761?pr=791
Pinning the version fixes the issue until we figure out what is going on and make changes on ansys-sphinx-theme side. First two examples above now running fine with the fix:
https://github.com/ansys/pyaedt/actions/runs/14713307643/job/41290910358?pr=6078
https://github.com/ansys/pymapdl/actions/runs/14713554947/job/41291659271?pr=3875
FYI doc-build on this PR will still fail since we are referencing main before merging. So just override.
=> fix: pin quarto version

check-vulnerabilities/requirements.txt, doc/source/changelog/806.fixed.md
Changes introduced in https://github.com/ansys/actions/pull/780/ are no longer required. Packages are now compatible.
=> fix(vulnerabilities): remove marshmallow dependency limit

build-wheelhouse/action.yml, doc/source/changelog/807.fixed.md
This pull-request adds the working-directory input so mono-repos can build the wheelhouse for its various libraries, as the working-directory input is not supported by GitHub with the uses syntax.
=> fix(wheelhouse): allow to specify working directory

_release-pypi/action.yml, build-library/action.yml, build-wheelhouse/action.yml, check-licenses/action.yml, doc-changelog/action.yml, hk-package-clean-except/action.yml, hk-package-clean-untagged/action.yml, release-github/action.yml
Some of our actions do not create venvs. For these actions, an extra flag needs to be passed to `uv` so it targets the python interpreter on the path.
Failed run: https://github.com/ansys/actions/actions/runs/14926657936/job/41933020321?pr=799
Testing this fix: https://github.com/ansys/actions/actions/runs/14927170869/job/41934585831?pr=799
=> fix: uv in actions without venv creation

build-wheelhouse/action.yml, doc/source/changelog/805.fixed.md
Fix #789 by installing from the `poetry.lock` file if present. This pull-request also adds the `working-directory` input so mono-repos can build the wheelhouse for its various libraries, as the `working-directory` input is not supported by GitHub with the `uses` syntax.
=> fix(wheelhouse): install from poetry.lock if present

.github/workflows/ci_cd_pr.yml, _doc-gen-robots/action.yml, _pr-doc-clean/action.yml, _pr-doc-deployment/action.yml, doc-deploy-pr/action.yml, doc/source/changelog/799.added.md, doc/source/doc-actions/examples/doc-deploy-pr.yml, doc/source/doc-actions/index.rst
Closes #694, closes #327.
The current implementation unifies the _**deployment of the pr documentation**_ and _**pr documentation cleanup after pr closure**_ into a single action, the intention is to make the configuration required of the consuming workflow easy.
The typical configuration changes required for a consuming workflow will be as illustrated in [this example](https://github.com/ansys/actions/pull/802/files).
In the current implementation, a comment is added to the pr pointing the user to the deployed documentation (this happens only once i.e. when the documentation is freshly deployed, which is when the pr is first opened, or when it is first re-opened). A comment is also added when the pr is closed (either by merging or otherwise) letting the user know that the pr …
=> feat: pr documentation deployment and cleanup

build-library/action.yml, doc/source/changelog/820.added.md
Allow to specify the working directory where the library is located. Useful when using this action in monorepos. Related with https://github.com/ansys/actions/pull/807.
=> feat(build-library): allow to specify working-directory

_pr-doc-deployment/action.yml, doc-deploy-pr/action.yml, doc/source/changelog/823.added.md, doc/source/doc-actions/examples/doc-deploy-pr.yml
Provides a default mechanism allowing users of `ansys/actions/doc-deploy-pr` to limit the number of pull request documentation that can be deployed.
Test: see https://github.com/ansys-internal/test-repo-moe/pull/7 and https://github.com/ansys-internal/test-repo-moe/pull/8
=> feat: option for maximum number of pr doc deployment

.github/dependabot.yml, _setup-python/action.yml, check-actions-security/action.yml, doc/source/changelog/825.maintenance.md
While checking the current main status this warning appeared
Seems like the default glob pattern have been updated and we could leverage that to match our default behavior (use of `pyproject.toml`). Also:
- Action `astral-sh/setup-uv` was not tracked by dependabot so it has been added.
- A new input has been added to `actions/_setup-python` to allow state if `uv` cache should be pruned or not. The default value is following `setup-uv`'s default behavior, see https://github.com/astral-sh/setup-uv?tab=readme-ov-file#disable-cache-pruning for more information.
=> chore: update uv settings

build-wheelhouse/action.yml, doc/source/changelog/826.fixed.md
This PR strengthen the compatibility of the `build-wheelhouse` action with `poetry`.
Currently, if one uses the main branch, the following error might appear https://github.com/ansys/pydpf-composites/actions/runs/15046028749/job/42288662063. Long story short, `pip freeze` doesn't use the revision defined in the poetry lock file and that can lead to a failure when building the wheelhouse. In the workflow failure, the project was installed with revision "1453403c76957981c84432cf67b43932ca9e99a5" while pip freeze doesn't contain this information and leads to the latest reference in main, i.e. revision "06170e14d2f47a9e53b59015b72e7b0dd897af9c".
This changes are successfully tested in https://github.com/ansys/pydpf-composites/actions/runs/15069361200
=> fix: build wheelhouse with poetry

_doc-build-linux/action.yml, doc/source/changelog/845.dependencies.md, doc/source/changelog/856.dependencies.md
While testing new changes, I found that the latest version of `awalsh128/cache-apt-pkgs-action` leads to errors on some packages, see https://github.com/awalsh128/cache-apt-pkgs-action/issues/159
Since `v1.5.0` is tagged as `pre-release` version, we should probably downgrade until it gets fixed and a stable release is released.
=> build(actions): downgrade awalsh128/cache-apt-pkgs-action due to errors

build-wheelhouse/action.yml, doc/source/changelog/861.maintenance.md
Closes #859.
I propose keeping what was initially done by @SMoraisAnsys (i.e. current behavior of `smoke-test-module`) and simply adding an output like @germa89 suggested for custom smoke testing.
That is simple and avoids having to cram several smoke test lines into one single string input.
Tested and working: https://github.com/ansys/pymapdl/actions/runs/15282156639?pr=3959
=> chore: improve smoke tests handling

doc/source/changelog/862.maintenance.md, release-github/action.yml
As title says. Since the SBOM are mandatory now, we should add them as part of the Github release artifacts.
=> chore: add SBOM artifacts to github release

.github/workflows/ci_cd_release.yml, doc/source/changelog/860.added.md
This PR introduces a minor change to the release process of the ``ansys/actions`` project as requested in #813: A short message is prepended to the release notes, containing a link to the section of the migration guide (https://actions.docs.ansys.com/version/stable/migrations/index.html#migration-guide) for the current major version and warning users for potential breaking changes when updating actions from a prior (major) version. 
Going forward, this short message will be provided in the release notes of every new release (not only the first one of a new major version).
This small feature is implemented in an attempt to enhance the information provided to individual project owners making use of ``ansys/actions``, in particular in the context of dependency upgrades triggered by …
=> feat: Prepend link to migration guide in GitHub release notes

_release-pypi/action.yml, doc/source/changelog/880.fixed.md
This is causing the release to PyPI action to fail. We need to fix it and patch release.
=> fix: missing environment variable on PyPI releasing

_release-pypi/action.yml, doc/source/changelog/884.fixed.md
We are also missing the proper handling of the ``--skip-existing`` command. This requires a patch release as well
=> fix: missing skip-existing command handling

doc/source/changelog/883.fixed.md, release-pypi-public/action.yml, release-pypi-test/action.yml
Related with #882. Raises a deprecation warning if not using the trusted publishers solution when releasing a package to the public domain.
=> fix(release-actions): raise warning if not using trusted publishers

doc/source/changelog/896.documentation.md, doc/source/migrations/index.rst
Document the situation faced in #895 when installing pre-releases with `uv`.
=> docs(prerelease): document installation by uv

_doc-build-linux/action.yml, doc/source/changelog/900.fixed.md
Fix #898 by using the right variable name when passing sphinx options at build time.
=> fix(doc-build): wrong variable name for sphinx options

build-wheelhouse/smoke_test.py, doc/source/changelog/908.added.md
This PR will improve the error message when smoke tests are failing.
At the moment, the message only mentions ``Could not find a module in 'package_name' with attribute '__version__'`` even if the error comes from the library import. An example is visible with [pyansys-sound](https://github.com/ansys/pyansys-sound/actions/runs/15604481469/job/43950655238).
=> feat: improving error message for smoke tests

.github/dependabot.yml, doc/source/changelog/915.maintenance.md
The cooldown feature is out of beta and should be working for github actions, see https://github.com/dependabot/dependabot-core/issues/3651#issuecomment-3006962980
=> ci: Use dependabot cooldown for pip and github actions

check-environment-approval/action.yml, doc/source/changelog/930.documentation.md
Certain sections in GH's docs that were being pointed to no longer exist / have been moved to different locations. This is causing linkcheck failures e.g. in https://github.com/ansys/actions/actions/runs/16289420495/job/46072877288?pr=925 and https://github.com/ansys/actions/actions/runs/16370307355/job/46472413092?pr=929.
This PR fixes that.
=> docs: replace broken links with correct ones

doc-build/action.yml, doc-deploy-pr/action.yml, doc/source/changelog/943.fixed.md
feat/extend-testing references were not changed to main before merging #929
=> fix: correct deleted branch references

doc/source/changelog/948.fixed.md, python-utils/release_github_utils.py
As the title.
See #946
Close #946
=> fix: remove unnecessary tag and date from release notes

.github/workflows/ci_cd_night.yml, doc/source/changelog/947.maintenance.md
Following the changes in #929, the package for the nightly release test has been updated to `ansys-actions-flit`. Note that it is not possible to test the release of `ansys-actions-poetry` from the same workflow file and I don't think it is necessary to split the nightly workflow into two like we did in #929.
=> ci: update ci_cd_night workflow

.github/workflows/ci_cd_pr_flit.yml, .github/workflows/ci_cd_pr_poetry.yml, doc/source/changelog/960.maintenance.md
Some jobs were not prevented to run when a PR was opened by dependabot.
This PR ensures that manual approval is accepted for such cases.
Close #959
=> ci: ensure manual approval on pr workflows

check-vulnerabilities/requirements.txt, doc/source/changelog/971.dependencies.md
As title says. Might not be needed if https://github.com/pyupio/safety/pull/779 get merged quickly
Close #970
=> build: temporary pin `typer` dependency (transitive)

.github/workflows/ci_cd_night.yml, .github/workflows/ci_cd_pr_flit.yml, .github/workflows/ci_cd_pr_poetry.yml, .github/workflows/ci_cd_release.yml, _release-pypi/action.yml, doc/source/changelog/983.fixed.md, doc/styles/config/vocabularies/ANSYS/accept.txt
Pin twine to v6.1.0 until we adjust the code to work for v6.2.0
=> fix: Pin twine to <6.2.0 and bump pypa action

doc/source/changelog/986.miscellaneous.md, doc/source/changelog/986.test.md, python-utils/test_versions.py, python-utils/versions.py
Imagine this scenario:
- A project has made `v0.11.0a0` and `v0.11.0b0` pre-releases.
- Then proceeds to patch `v0.10` for whatever reason.
The current logic will remove deployed documentation for the pre-releases and this shouldn't be the case. This PR fixes that.
=> test: add more pre-release tests

doc/source/changelog/1012.fixed.md, release-github/action.yml
Use base name instead of the relative path to the file.
Close #1011
=> fix: GitHub command-line tool command in ansys/release-github

doc/source/changelog/1030.documentation.md, doc/source/vulnerability-actions/index.rst
Fixing a minor typo I encountered in the file ``vulnerability-actions/index.rst``.
=> docs: Fix typo in ``vulnerability-actions/index.rst``
