code-style/action.yml
doc-style/action.yml

Convert into true reusable composite workflows.

FIX: composite workflows

---

code-style/action.yml
doc-style/action.yml

Impose a shell, as per [official documentation](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file).

FIX: impose shell in workflows

---

code-style/action.yml

FIX: inputs syntax

---

doc-build/action.yml

Addresses for documentation building, as per #1.

FEAT: add doc-build action

---

doc-build/action.yml

FIX: doc-build syntax

---

doc-deploy-stable/action.yml

Ignore staging files when there is nothing to stage.

FIX: push only to gh-pages when unstaged files

---

build-ci-wheels/action.yml

Update condition for build wheel.

Change ``if`` and ``and`` condition in ci build wheel actions. 

---

doc-build/action.yml
doc/source/conf.py
doc/source/index.rst
doc/source/tests-actions/index.rst
doc/styles/Vocab/ANSYS/accept.txt
tests-pytest/action.yml

This pull-request adds a pytest action that accepts markers, options and post-arguments.

FEAT: add tests-pytest action

---

build-wheelhouse/action.yml
doc/source/build-actions/index.rst
doc/source/conf.py
doc/source/tests-actions/index.rst

Fix #1 by adding the wheelhouse action.

FEAT: wheelhouse action

---

doc-deploy-stable/action.yml

Quick fix on the command triggering the execution of the version switcher file.

FIX: version switcher script name

---

.github/workflows/ci_cd.yml
.pre-commit-config.yaml
doc-deploy-to-repo/action.yml
doc/source/conf.py
doc/source/doc-actions/index.rst

FEAT: Deploy documentation to a specific repository

---

doc/source/doc-actions/index.rst

DOC: Missing docs for doc-deploy-to-repo action

---

build-ci-wheels/action.yml
build-library/action.yml
build-wheelhouse/action.yml
code-style/action.yml
doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml
doc-deploy-to-repo/action.yml
doc-style/action.yml
doc/source/tests-actions/index.rst
release-github/action.yml
release-pypi-private/action.yml
release-pypi-public/action.yml
release-pypi-test/action.yml
tests-pytest/action.yml

Some minor typos. This pull-request adds periods at the end of the argument descriptions, includes some missing names in the actions and makes sure all descriptions are surrounded by double quotes.

DOC: fix descriptions and typos

---

.github/workflows/ci_cd.yml

Update CI according to #69 and #70.

CI: update to new action inputs

---

build-wheelhouse/action.yml

Accepting additional targets in wheel build

---

doc-build/action.yml

Implement usage of awalsh128/cache-apt-pkgs-action

---

scripts/version_mapper.py

Opening this as per https://github.com/ansys/ansys-sphinx-theme/pull/161. We identified the `announcement.html` is not being copied within the outdated folders.

DBG: debugging announcement creation

---

scripts/version_mapper.py

DBG: debugging announcement creation II

---

scripts/version_mapper.py
tests/tests_scripts/test_version_mapper.py

FEAT: do not required an announcement template

---

doc-deploy-stable/action.yml

FIX: regex in doc-deploy-stable

---

.github/dependabot.yml
requirements/requirements_doc.txt

CI: enable pip ecosystem in dependabot

---

.github/workflows/ci_cd.yml
doc/source/conf.py

Fix #107 by:
- Adding a `DOUMENTATION_CNAME` within the `ci_cd.yaml` file.
- Reading its value from the `conf.py` file.
- Using it in the `versions` vairable.
- Deprecating the `get_version_match` function in favor of the one implemented in the theme.

MAINT: update cname and versions.json content

---

.pre-commit-config.yaml
README.rst
build-wheelhouse/action.yml
doc-deploy-stable/action.yml
doc/source/build-actions/index.rst
doc/source/conf.py
doc/source/doc-actions/index.rst
doc/source/index.rst
requirements/requirements_doc.txt
scripts/version_mapper.py

Modify index page

---

doc-deploy-stable/action.yml

FIX: curl scripts from right branch

---

README.rst
build-ci-wheels/action.yml
build-library/action.yml
build-wheelhouse/action.yml
check-licenses/action.yml
code-style/action.yml
doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml
doc-deploy-to-repo/action.yml
doc-style/action.yml
tests-pytest/action.yml

Fixing checkout option

---

check-licenses/action.yml
doc-build/action.yml

Invalid multiple condition for docs-build action

---

doc-deploy-dev/action.yml

FIX: Remove name input argument - not being used

---

doc-deploy-dev/action.yml

This should fix: https://github.com/ansys/ansys-tools-pre-commit/actions/runs/3872172731/jobs/6600938753
Close #130

Removing defaults for download action arguments

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

Fixes #143 by allowing users to specify if documentation artifacts should be decompressed or not.

FIX: indicate whether to compress/decompress artifacts

---

build-ci-wheels/action.yml
build-library/action.yml
build-wheelhouse/action.yml
check-licenses/action.yml
code-style/action.yml
doc-build/action.yml
doc-deploy-stable/action.yml
doc-deploy-to-repo/action.yml
doc-style/action.yml
tests-pytest/action.yml

Skip json build for docs build.

---

doc-build/action.yml

Fixes the issues found in https://github.com/ansys/ansys-sphinx-theme/actions/runs/3987699947/jobs/6837892451. A continuation of the work made in #146.

FIX: shell script syntax

---

scripts/version_mapper.py
tests/tests_scripts/test_version_mapper.py

Add a `/` at the end of every URL

---

LICENSE
doc/source/conf.py
tests/pyansys-actions/LICENSE

Fixes the copyright years in the project.

FEAT: use datetime to compute copyright in doc

---

doc/source/conf.py

This pull-request updates the reference to the "versions.json" file in the "conf.py" file.

FIX: link to 'verions.json' file

---

requirements/requirements_doc.txt

As per title of the pull-reuquest, just updating to the latest version.

MAINT: update ansys-sphinx-theme==0.9.2

---

hk-package-clean-except/action.yml
hk-package-clean-untagged/action.yml

Allowing last N-Days on hk-package actions

---

.github/workflows/ci_cd.yml
.pre-commit-config.yaml
doc/source/conf.py
requirements/requirements_doc.txt

Update `release/2.0` to use the latest:
* Documentation theme
* Multi-version layout
* Deployment actions

DOC: update to latest multi-version docs

---

doc-deploy-dev/action.yml

Very limited modifications to the description of some actions.

Typo in the actions description.

---

release-github/action.yml

Using single quotes to fix the conditional syntax.

FIX: release-github syntax

---

release-github/action.yml

As per the issues in found in [this CI/CD log](https://github.com/pyansys/pyansys-tools-versioning/actions/runs/4290831992/jobs/7475369013#step:3:317).

FIX: release-github action

---

doc-deploy-stable/action.yml

Fixing docs publish from release branch

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

FIX: make 'force-orphan' optional

---

_release-pypi/action.yml
release-github/action.yml
release-pypi-private/action.yml
release-pypi-public/action.yml
release-pypi-test/action.yml

As title says. Arguments should be booleans.

Solving dry-run issues

---

release-github/action.yml

Solving issues in release phase

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

Fix the link to multidoc in dev guide, found broken.

Doc: fix the broken links.

---

branch-name-style/action.yml

Fixes the syntax errors raised in pull-request #226.

FIX: syntax for branch-name-style action

---

branch-name-style/action.yml

FIX: syntax for branch-name-style

---

branch-name-style/action.yml

FIX: conditional syntax

---

doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml
tests-pytest/action.yml

Following https://github.com/actions/runner-images/issues/7452

FIX: update apt-get

---

doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml
tests-pytest/action.yml

FIX: sudo apt-get update requires sudo

---

commit-style/action.yml

fix: execute commit-style only on PRs

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

This pull-request fixes the issues originated in https://github.com/pyansys/actions/actions/runs/4893744139

fix: action name

---

_doc-gen-versions-page/action.yml

FIX: declare html file

---

hk-package-clean-except/action.yml
hk-package-clean-untagged/action.yml

As title says... we made a big mistake

fix: error in if condition for package cleanup

---

_doc-gen-versions-page/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

Continuation of #253. Giving a try to the JS approach.

fix: versions page generation

---

_doc-gen-versions-page/action.yml

Finally, this fixes the version index page. Continuation of #258.

fix: versions index page

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

Fixes the logic when decompressing the artifacts in the actions.

fix: avoid extra dir when decompressing

---

doc-build/action.yml

feat: enable link check as an optional input

---

build-wheelhouse/action.yml
check-licenses/action.yml

feat: add check-licenses to wheelhouse

---

doc-build/action.yml

feat: default link check when building docs

---

README.rst

fix: headers and indentation

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

Partially solves #284 
This will allow end users to define their own title and description for the redirect index.html file

feat: allowing redirection title and description

---

check-licenses/action.yml

Solves issues with check-licenses running on Windows

fix: install wget on Windows

---

check-licenses/action.yml
check-licenses/ignored-packages.txt

fix: accept PSF packages (typing_extensions and pywin32)

---

build-wheelhouse/action.yml

As title says. This will also improve the comparisons made.

fix: remove the use of bc

---

check-licenses/ignored-packages.txt

feat: add reuse and order ignored packages

---

.github/workflows/ci_cd.yml

feat: solve issues with env var for org level

---

.github/workflows/ci_cd.yml
doc/source/conf.py
requirements/requirements_doc.txt

fix the key issue with pymeilisearch scraping

fix: index the documentation for pymeilisearch

---

.github/workflows/ci_cd.yml

Fixes the issue raised in https://github.com/ansys/actions/actions/runs/5782950550/job/15670887761

fix: doc-deploy-index in CI/CD

---

doc-deploy-index/action.yml

Add stop urls as sphinx options

fix: add additional options to pymeilisearch

---

_doc-gen-versions-page/action.yml

Fix the issues raised in https://github.com/ansys/actions/actions/runs/5948898594/job/16133718203

fix: doc version page generator

---

check-vulnerabilities/action.yml
doc/source/index.rst
doc/source/vulnerability-actions/examples/check-vulnerabilities-basic.yml
doc/source/vulnerability-actions/examples/check-vulnerabilities-dev-mode.yml
doc/source/vulnerability-actions/index.rst

feat: adding a new vulnerability detection action

---

check-vulnerabilities/action.yml
doc/source/index.rst

fix: minor issues with action

---

.github/workflows/ci_cd.yml
build-ci-wheels/action.yml
build-library/action.yml
build-wheelhouse/action.yml
check-licenses/action.yml
check-vulnerabilities/action.yml
code-style/action.yml
doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml
doc-style/action.yml
tests-pytest/action.yml

Solves the issues caused by the latest update of this action.

fix: update to actions/checkout@v4

---

build-wheelhouse/action.yml

Reported by @greschd - related to https://github.com/ansys/pyansys/discussions/373#discussioncomment-7141170

fix: bug in wheelhouse generation

---

_doc-gen-sitemap/action.yml

- Remove ``www`` sub domain from the url in sitemap
- Add the version directory in the additional page location in the site map see https://github.com/ansys/pymapdl/blob/543819dd29d6e15e2c67c477eebf4e664c4d0e32/sitemap.xml#L16

fix: sitemap url

---

doc-style/action.yml

Had to rename branch name - coming from #360

chore: bump doc-style vale version (2.29.6)

---

build-ci-wheels/action.yml
build-library/action.yml
build-wheelhouse/action.yml
check-vulnerabilities/action.yml
doc-build/action.yml

chore: update upload-artifacts to v4

---

doc-deploy-stable/action.yml

Fix missing version in private action.

fix: missing version in action

---

_setup-python/action.yml

As per internal discussion, this pull-request fixes the version of the actions/setup-python.

fix: update actions/setup-python@v5

---

code-style/action.yml

Closes #395 
mypy requires dependencies and project to be installed. By default we will skip the installation of the library but if repos need it they can set
```skip-install: false```

feat: allow project installation

---

code-style/action.yml

fix: venv not activated in Windows runners

---

.pre-commit-config.yaml
LICENSE
_doc-gen-sitemap/action.yml
_doc-gen-versions-page/action.yml
_logging/action.yml
_release-pypi/action.yml
_setup-python/action.yml
branch-name-style/action.yml
build-ci-wheels/action.yml
build-library/action.yml
build-wheelhouse/action.yml
check-licenses/action.yml
check-vulnerabilities/action.yml
code-style/action.yml
commit-style/action.yml
doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-index/action.yml
doc-deploy-stable/action.yml
doc-style/action.yml
docker-style/action.yml
hk-package-clean-except/action.yml
hk-package-clean-untagged/action.yml
release-github/action.yml
release-pypi-private/action.yml
release-pypi-public/action.yml
release-pypi-test/action.yml
tests-pytest/action.yml

adding license headers to all actions

feat: add License headers to actions

---

docker-style/action.yml

Fixes the rendering issues in https://actions.docs.ansys.com/version/stable/style-actions/index.html#docker-style-action

fix: rendering of action description

---

doc/source/migrations/docs-style-vale-version-update.rst

fix: migration doc code block

---

.github/workflows/ci_cd.yml

As title says... follow up from #480

fix: typo in ci/cd

---

doc-changelog/action.yml
doc-deploy-changelog/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

Recent changes related to pyansys-ci-bot conflicted with the action way of working. This should patch it.

fix: email address in doc-changelog and doc-deploy*

---

build-ci-wheels/action.yml

update the build ci wheels actions  and drop support of 3.8

fix: update the build-ci wheels actions

---

check-licenses/action.yml
doc-build/action.yml
doc-deploy-dev/action.yml
doc-deploy-stable/action.yml
release-pypi-private/action.yml

fix issue with redirection to dev in #536 
fix indentation of admonitions

fix: indentation with docs and redirection to dev for static js file in docs deploy action

---

check-licenses/ignored-packages.txt

As title says. Email thread available internally (ping me for further details)
Pinging @mariostieriansys for visibility. Once the PR is merged, your checks should pass.

feat: usage of usd-core has been approved by legal department

---

.github/workflows/ci_cd.yml

WIP to fix the current issue of sharing the same environment for testing pypi and releasing to the official pypi.

ci: fix test to pypi

---

check-pr-title/action.yml

fix: metadata name of check-pr-title action

---

_doc-build-windows/action.yml

feat: verify docs have been generated properly on Windows

---

tests-pytest/action.yml

Standarizing virtual environment creation based on OS and decoupling problems from observed behavior on Windows GitHub runners
See run: https://github.com/ansys-internal/allie-clients-python/actions/runs/11156816834

fix: solving issues in ``actions/tests-pytest`` action

---

tests-pytest/action.yml

Using ansys/actions/tests-pytest leads to failures on poetry projects. Adapting.

fix: poetry tests runs failing

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

fix: redirect for search.json file

---

doc-deploy-dev/action.yml
doc-deploy-stable/action.yml

fix: search file variable names

---

doc/source/conf.py

As title says... the doc build has started to fail. My feeling is that they must have implemented some protection against bots.

fix: unreachable link

---

doc/source/index.rst

feat: adapt style to UI/UX guidelines and typo

---

doc-deploy-dev/action.yml

https://github.com/ansys/ansys-sphinx-theme/issues/571#issuecomment-2443923015

fix: landing page search 

---

.ci/ansys-actions/pyproject.toml

fix: demo library README is still rst

---

build-ci-wheels/action.yml

feat: upgrade cibuildwheel version

---

check-licenses/action.yml

Improving retrieval from summary view by just looking at the information needed.

feat: improve license checker by just retrieving the needed lines

---

python-utils/default_template.jinja

in favor of https://github.com/ansys/pre-commit-hooks/pull/294/files

fix: whitespace control in changelog template

---

_logging/action.yml

I left a typo in #704, this should fix it.

fix: if statement condition in logging

---

SECURITY.md
doc/source/changelog/709.documentation.md

This pull-request targets at #581 by including a `SECURITY.md` file.

docs(metadata): add SECURITY.md

---

.github/workflows/ci_cd_release.yml
doc-changelog/action.yml
doc-deploy-changelog/action.yml
doc/source/changelog/715.fixed.md

This pull-request fixes the issues raised in https://github.com/ansys/actions/actions/runs/13657128302/job/38179054293 by allowing the changelog action to work with non-Python projects.

fix(changelog): avoids installing project and provides support for non-python projects

---

.github/workflows/ci_cd_release.yml
doc/source/changelog/717.fixed.md

Fixes the content of the `MAJOR` variable in the rolling release logic.

fix(doc): major variable

---

doc/source/changelog/718.documentation.md
doc/source/migrations/index.rst

Adding additional content to the v8.2 new features.

docs: extend v8.2 new features notes

---

.github/workflows/ci_cd_release.yml

Fix the issues raised in https://github.com/ansys/actions/actions/runs/13782426909

ci(release): fix changelog deployment

---

.github/workflows/ci_cd_release.yml
doc/source/changelog/727.maintenance.md

Fix the issues raised in https://github.com/ansys/actions/actions/runs/13782730639/job/38543808278

ci(release): fix github variable

---

doc/source/changelog/737.documentation.md
doc/source/migrations/index.rst
release-github/action.yml

docs: fix vale warning on CLI term

---

doc/source/changelog/740.documentation.md
doc/source/migrations/index.rst
doc/styles/config/vocabularies/ANSYS/accept.txt

docs: add documentation on automerge action

---

doc/source/changelog/748.maintenance.md
release-github/action.yml

chore: clarify comment statement on release-github action

---

.github/workflows/ci_cd_release.yml
doc/source/changelog/766.fixed.md

Related to failed release workflow: https://github.com/ansys/actions/actions/runs/14337009161/job/40186563773

fix: tag check

---

.github/workflows/ci_cd_pr.yml
doc/source/changelog/774.maintenance.md

Coming from experience in #770

ci: rewrite dependabot checks

---

.github/workflows/ci_cd_release.yml
doc/source/changelog/800.fixed.md

fix: ci_cd_release action

---

.github/labeler.yml
.github/labels.yml
.github/workflows/ci_cd_pr.yml
doc/source/changelog/802.maintenance.md
doc/source/index.rst

(Edited by @jorgepiloto)
This pull-request implements the `ansys/actions/doc-deploy-pr` action in the pipelines of the project.

ci: use ansys/actions/doc-deploy-pr

---

doc-deploy-dev/action.yml
doc/source/changelog/830.maintenance.md

ci: remove deprecated line

---

doc-deploy-changelog/action.yml
doc/source/changelog/837.added.md

feat: change branch naming in changelog action

---

build-wheelhouse/action.yml
check-licenses/action.yml
doc/source/changelog/853.fixed.md

After investigations, this might be causing it. Let's align the criteria

fix: check licenses logic alignment

---

build-wheelhouse/smoke_test.py
doc/source/changelog/875.fixed.md

As title says. Coming from investigations of https://github.com/ansys/pydpf-composites/actions/runs/15413810342/job/43376310699

fix: smoke test for poetry projects in editable mode

---

doc/source/changelog/879.documentation.md
doc/source/migrations/index.rst

docs: use bash shell for windows

---

_doc-build-windows/action.yml
doc/source/changelog/888.fixed.md

Closes #887
We were not dealing properly with the outputs.

fix: doc build on windows input issues

---

_release-pypi/action.yml
doc/source/changelog/905.miscellaneous.md

Removing unnecessary usage of `echo`.

refactor: Remove unnecessary echo

---

doc/source/changelog/934.fixed.md
python-utils/parse_pr_title.py

fix: capitalization of changelog fragments

---

.ci/ansys-actions-flit/pyproject.toml
.ci/ansys-actions-poetry/poetry.lock
.ci/ansys-actions-poetry/pyproject.toml
doc/source/changelog/951.fixed.md

Related to https://github.com/ansys/actions/security/dependabot/1

fix: dependabot security alert

---

.github/workflows/ci_cd_pr.yml
doc/source/changelog/969.fixed.md

Doc build job was always running on Linux. This fixes that.

fix: correct ci_cd_pr.yml configuration

---

doc/source/changelog/1003.documentation.md
doc/source/conf.py
doc/source/migrations/index.rst

docs: improve migration guide

---

check-actions-security/action.yml
doc/source/changelog/1020.fixed.md

fix: add always() condition to the last step of check-actions-security
